apiVersion: skaffold/v2alpha3
kind: Config 
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false      
  artifacts:
    - image: abhi149209/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: abhi149209/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .        
    - image: abhi149209/comments
      context: comments 
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: . 
    - image: abhi149209/event 
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: . 
    - image: abhi149209/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .        

     

      
