apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"posts-clusterip-srv","namespace":"default"},"spec":{"ports":[{"name":"posts","port":4000,"protocol":"TCP","targetPort":4000}],"selector":{"app":"posts"}}}
  creationTimestamp: "2022-12-04T14:27:17Z"
  name: posts-clusterip-srv
  namespace: default
spec:
  clusterIP: 10.107.10.206
  clusterIPs:
  - 10.107.10.206
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: posts
    port: 4000
    protocol: TCP
    targetPort: 33027
  selector:
    app: posts
  sessionAffinity: None
  type: ClusterIP
